### ISSUE TITLE
How to know DtisCnt value when template_dependency_structure is not present

### ISSUE THREAD

**Issue by murillo128** [AOMediaCodec/av1-rtp-spec#153]
Currently we have:

```
  template_dependency_structure_present_flag = f(1)
  active_decode_targets_present_flag = f(1)
  custom_dtis_flag = f(1)
  custom_fdiffs_flag = f(1)
  custom_chains_flag = f(1)

  if (template_dependency_structure_present_flag) {
    template_dependency_structure()
    active_decode_targets_bitmask = (1 << DtisCnt) - 1
  }

  if (active_decode_targets_present_flag) {
    active_decode_targets_bitmask = f(DtisCnt)
  }
}
```

`DtisCnt` is calculated inside `template_dependency_structure()`, so if `template_dependency_structure_present_flag` is `false` but `active_decode_targets_present_flag` is `true` there is no way to calculate the `DtisCnt` value.

From libwebrtc code it seems that the last received iframe `DtisCnt` is used instead:

https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/video/rtp_video_stream_receiver.h;l=345;drc=c70af83bc44f6829277cdc3621e7015d6e0d7530;bpv=1;bpt=1

IMHO it is not a good pattern to have to rely on previous packets data to parse a header extension. What would happen if the iframe is lost and I am trying to decode this packet? or if the iframe is lost and the structure is changed?

**Comment by DanilChapovalov** [comment]
If i-frame is lost, then DD is unparsable. That is by design to reduce overhead.
The idea is that such packet is not very useful without key frame anyway, so it should be stashed until first packet of the i-frame is received. (libwebrtc currently implements alternative simpler, but less efficient solution: drop such a packet, then request a resend once i-frame is received.)
There is much more than DtisCnt and ChainCnt in the the i-frame: templates. very little is known about the packet without the template definition.

when iframe is lost, but structure is changed, different template ids should be used. That doesn't allow to parse the DD, but allows to detect when DD is unparsable. There is note about that next to frame_dependency_template_id in the https://aomediacodec.github.io/av1-rtp-spec/#a42-semantics

**Comment by murillo128** [comment]
None of the other existing rtp header extensions requires keeping state for
parsing.

It is fine to not be able to use the info in the DD without previous DDs,
but parser should be stateless.

**Comment by murillo128** [comment]
Regarding the overhead, using custom dtis and/or chains the extra overhead is already:

```
  if (result.need_custom_dtis) {
    result.extra_size_bits +=
        2 * descriptor_.frame_dependencies.decode_target_indications.size();
  }
  if (result.need_custom_chains)
    result.extra_size_bits += 8 * structure_.num_chains;
```

adding the dti count is 5 bits and the chain counts is 6 or 7 bits depending on the value.

**Comment by DanilChapovalov** [comment]
Can you please clarify what do you mean by "parsing" in this case?

Process described in section A.4.1 will still require state even with added fields for DtiCnt and ChainCnt. That process require other variables from the first packet of a key frame like template_id_offset or TemplateFdiff[]

Extracting minimum information (e.g. bof end eof flags) can be done in stateless way.

Will it help to rewrite the process described in A.4.1 into two phases: first phase is stateless, second one is stateful?

(stateful parsing is not something that is completely new. e.g. GOF in VP9 descriptor is a state that is sent once and then regularly referred to)

**Comment by murillo128** [comment]
I consider the section of A.4.1 to cover just more than "syntax" as it defines the logic on how to manage estate to calculate the final output. That is quite uncommon for the typical RTP rfc.

I personally prefer to do a strict parsing (i.e. just serializing/deserializing) without applying the logic to apply the logic.

For example in the case that the custom dtis are used, my parser does not produce the new dependency structure based on past structure and the custom dtis present on the DD, but just return the custom dtis
```
	std::optional<TemplateDependencyStructure> templateDependencyStructure;
	std::optional<std::vector<bool>> activeDecodeTargets;
	
	std::optional<std::vector<DecodeTargetIndication>> customDecodeTargetIndications;
	std::optional<std::vector<uint32_t>> customFrameDiffs;
	std::optional<std::vector<uint32_t>> customFrameDiffsChains;
```
https://github.com/medooze/media-server/blob/master/include/rtp/DependencyDescriptor.h#L73
https://github.com/medooze/media-server/blob/master/src/rtp/DependencyDescriptor.cpp#L416

In this regards, I am doing the annex A.4.1 syntax in two phases, first the (almost) stateless parsing (if we include the dtis count/chain diff count) and a state full process to determine which is the actual frame dependency structure being used.

This allows me to write easier unitary tests and split the logic more easily (at least for me).

**Comment by lminiero** [comment]
> If i-frame is lost, then DD is unparsable. That is by design to reduce overhead.
> The idea is that such packet is not very useful without key frame anyway, so it should be stashed until first packet of the i-frame is received

I'm most definitely not going to keep a packet for a long time, hoping to receive the i-frame it is based on sooner or later, just so that I can decide whether or not that packet should be relayed in the first place. An SFU should not buffer packets like that, but just relay in a selective way: let me relay the packet, and let the recipient buffer if they want until they have enough info to decode. I disagree that it will reduce overhead: it will likely increase it instead, as holding on that packet and send others will instead cause the peer to send us NACKs (it will be lost to them) and mess up RTCP stats too. Besides, if I stashed a lot of packets because I missed the i-frame, as soon as the i-frame is received I'll have to shove a lot of traffic (the already large i-frame followed by all the packets I held onto) to the recipient(s) in a very bursty way, which can be a serious issue if I have to do the same for a lot of recipients. Not to mention the fact that this delayed delivery process is going to have a serious impact on almost all SFUs out there, in terms of memory usage and state management, because it forces them to do buffering.

I personally strongly disagree with this reliance on info in previous packets to decide what to do with what I just received. As Sergio said, this is very different from how RTP extensions work today.

**Comment by murillo128** [comment]
I definitively underestimated the impact of the changes in my code.

I have run into a chicken an egg situation. To parse the rtp packet I need the previous received template structure, but to be able to get the associated RTP stream for the packet in which it is stored, I need to parse the rtp header extensions to obtain the mid/rid/rrid/etc. 

So I can't parse the packet without heavily changing my code.

**Comment by agouaillard** [comment]
We still think the current design is not ideal, and will require heavy changes to SFUs.
However, we do not see any way to further convey the message through, nor to make the rparties involved change their mind. We implemented it, we want to move forward, let's drop it.

**Comment by lminiero** [comment]
Then I guess I will not implement it until I really have to. It's a pity, I would have loved to add support for it right away.
