### ISSUE TITLE
Is there any spec that defines f(n) and ns(n)?

### ISSUE THREAD

**Issue by murillo128** [AOMediaCodec/av1-rtp-spec#157]
There is no explanation about how the numbers are encoded using the "non-symmetric unsigned encoded integer with maximum number of values n", while the spec puts the pseudo code about how to read it, it lacks the information about how to write it, and reverse engineering the algorithm doesn't seem the way forward.

Would be good to either reference where they are defined or add mor information about the encoding works and how to write both of them.

**Comment by DanilChapovalov** [comment]
These two functions are borrowed from the main av1 spec:
https://aomediacodec.github.io/av1-spec/av1-spec.pdf
Section 4.10.2 f(n)
Section 4.10.7 ns(n)

**Comment by murillo128** [comment]
I think that the correct algorithm of writing the non-symmetric unsigned encoder integer is:
```
write_ns(n,v) {
  assert(n>1)
  w = 0
  x = n
  while (x != 0) {
    x = x >> 1
    w++
  }
  m = (1 << w) - n
  if (v< m)
    write(w - 1, val);
  else
    write(w, v + m) 
}

```

where `write(n,v)` writes the bit stream representation of `v` using `n` bits.

**Comment by DanilChapovalov** [comment]
That algorithm looks correct to me with one caveat:

n = 1 is valid and important edge case. When chains_cnt=1, then decode_target_protected_by are stored/read using ns(n=1), consuming 0 bits.
so probably instead of assert(n>1) it would be better to write
assert(n>v)
if (n == 1) return
though... that early return is not really necessary, rest of the function would work with n = 1 as long as write function supports writing 0 bits.

**Comment by murillo128** [comment]
yes, you are right

**Comment by StephenBotzko** [comment]
Resolved in Pull Request 169
