### ISSUE TITLE
Add algorithm for DT to layer mapping

### ISSUE THREAD

**Issue by murillo128** [AOMediaCodec/av1-rtp-spec#173]
As per #171 it should be possible to know which layer (<spatialId,temporalId> pair) corresponds to a decode target in order to be able to do layer forwarding based on content adaptation.

**Comment by DanilChapovalov** [comment]
just for the reference, such algorithm was in the spec already:
https://github.com/AOMediaCodec/av1-rtp-spec/commit/fd6b709d9997453c8cf9e3c8ae2e9c64f74984dd#diff-64c2d4848633540563bdf133493ccccf12e61f0dfa21341f377a2ddf2131b5cfL516

**Comment by murillo128** [comment]
The algorithm seems to do the opposite of what I need, given a DT know with is the max <sid,tid>. I need an algorithm that given a <sid,tid> decides which is the DT that needs to be forwarded. 

If we use the algorithm we would get a set of DTs, but I am not sure if it is safe to forward all of them and how the upswitch/downswitch will work in this case.

**Comment by DanilChapovalov** [comment]
For structures defined in webrtc-svc spec and all practical structures I'm aware about that mapping is 1:1,
i.e. it would work to create the reverse mapping.

For structures where several DTs maps to the same <sid, tid> old algorithm for content adaptation likely won't work any way.
I have one such theoretical structure in my mind, but there DD is used more for reliability rather than scalability.
For those structures application meaning of DT should likely map directly into DT index, bypassing (sid, tid).
Until there is a practical structure where we can better explore how it should behave I would say when there are several DTs for same <sid, tid>, SFM should select any DT, or better first decodable one - this way if stream producer would want SFM to select all of them, it can use a separate DT that is a union of those DTs.

Similarly 'upswitch/downswitch' concepts would usually work for existent cases, but not really defined in general case. Spatial scalability alone made those concepts a bit fuzzy (e.g. switch from S1T0 to S0T1 is upswitch or downswitch?)

**Comment by StephenBotzko** [comment]
Resolved in PR #178
